version: "3" 

services:
  api:
    #build: ./
    #image: "express-api:${TAG:-dev}"
    image: "node:8.10"
    networks:
      - express-test
    ports:
      - "${PORT:-3501}:3501"
    volumes:
      - ./:/app
    working_dir: /app
    command: npm start 
networks:
    express-test:
